# -*- coding: utf-8 -*-
"""to-do-list

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4nNLtdr6fgWzkPlnBSSt6XuPw7TMYYB

#To do List
"""

todo_list = []

while True:
    print("""
    원하는 작업의 번호를 입력하세요.
    1. 할 일 추가
    2. 할 일 수정
    3. 할 일 삭제
    4. 종료
    """)
    task = int(input("\n작업 선택: "))
    sc = 1 #while문 on을 위한 스위치 (0은 off, 1은 on)

    # 1번 입력 시 추가
    if task == 1:

        while sc == 1:
            todo = input("\n할 일 입력: (뒤로가기 B)")

            if todo.upper() == "B": #뒤로 가기
                sc = 0

            else:
                todo_list.append(todo) #할 일 추가하기
                for idx, t in enumerate(todo_list, 1):
                    print(f"{idx}. {t}")

    # 2번 입력 시 수정
    elif task == 2:
        #수정할 할 일 번호 선택
        while sc == 1:
            toedit = input("\n수정할 할 일의 번호를 입력하세요.: (뒤로가기 B)")

            if todo.upper() == "B":
                sc = 0
#코드
            else:

if len(todo_list == 0:
            print("할 일 목록에 데이터가 존재하지 않습니다.")

        else:






    # 3번 입력 시 삭제
    elif task == 3:
        if len(todo_list) == 0:
            print("할 일 목록에 데이터가 존재하지 않습니다.")

        else:
            while sc == 1:
                todel = int(input("\n삭제할 할 일의 번호를 입력하세요.: (뒤로가기 B)"))

#B 누르면 어떻게 될지 써야함

                if len(todo_list) < todel:
                    print("존재하지 않는 번호입니다.")

                else:
                    todo_list.pop(todel-1)

                    for idx, t in enumerate(todo_list, 1):
                        print(f"{idx}. {t}")
                    break #여기도 수정할지 말지 고민

    # 4번 입력 시 종료
    else:
        print("\n작업 종료")
        break

"""수정하는거랑 조회하는거 만들어야함
언제까지 할건지도 포함?
예쁘게 만드는건 아직?
"""